version: "2"
volumes:
  settings:
  cookies:
  cups:
services:
  redis:
    network_mode: host
    build: ./redis
  kiosk:
    build: ./kiosk
    depends_on:
      - "websocket"
      - "redis"
      - "cups"
    privileged: true
    labels:
      io.balena.features.supervisor-api: "1"
    network_mode: host
    volumes:
      - "settings:/data"
  websocket:
    privileged: true
    network_mode: host
    restart: always
    build: ./websocket
    depends_on:
      - redis
    ports:
      - "80"
      - "8888:8888"
    labels:
      io.balena.features.kernel-modules: "1"
      io.balena.features.firmware: "1"
      io.balena.features.dbus: "1"
      io.balena.features.supervisor-api: "1"
      io.balena.features.balena-api: "1"
  cups:
    build: ./cups
    ports:
      - "80"
    privileged: true
    restart: always
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    network_mode: host
    volumes:
      - "cups:/etc/cups"
    labels:
      io.balena.features.kernel-modules: "1"
      io.balena.features.firmware: "1"
      io.balena.features.dbus: "1"
      io.balena.features.supervisor-api: "1"
      io.balena.features.balena-api: "1"
