version: "2"
volumes:
  settings:
services:
  browser:
    build: ./browser
    privileged: true
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.supervisor-api: "1"
    network_mode: host
    volumes:
      - "settings:/data"
